### ISSUE TITLE
Update xdebug to 2.5.5

### ISSUE THREAD

**Issue by kofrezo** [gplessis/dotdeb-xdebug#2]
Hi Guillaume,
I tried to download latest Sourcecode of xdebug 2.5.5 and build new packages with this repository to provide you a PR to help but it failed with errors when just replacing the sourcecode directory with a extracted tarball from xdebug. Would it be possible to provide the latest version of xdebug on dotdeb it contains some important bugfixes.

**Comment by gplessis** [comment]
Xdebug 2.5.5 has been uploaded for Jessie
